# Generated by Django 5.2 on 2026-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
