# Generated by Django 5.2 on 2026-06-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_favourite_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='pieces',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во элементов'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер'),
        ),
    ]
