# Generated by Django 5.2 on 2026-06-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_address_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courier_comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
