# Generated by Django 5.2 on 2026-07-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('processing', 'В обработке'), ('shipped', 'В пути'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='pending', max_length=20),
        ),
    ]
